export const CATEGORIES = [
  { id: "yerba", name: "Yerba" },
  { id: "mate", name: "Mate" },
  { id: "bombilla", name: "Bombilla" },
  { id: "combo", name: "Combo" },
]

export const FEATURED_PRODUCTS = [
  {
    id: 1,
    name: "Yerba Gambetta Clásica",
    description: "Yerba mate tradicional con palo",
    price: 2500,
    category: "yerba",
    image: "/yerba-mate-package-traditional.jpg",
  },
  {
    id: 2,
    name: "Mate Imperial",
    description: "Mate de calabaza curado",
    price: 4500,
    category: "mate",
    image: "/traditional-mate-gourd-calabash.jpg",
    customizable: true,
    customizationPrice: 800,
  },
  {
    id: 3,
    name: "Bombilla Alpaca",
    description: "Bombilla de alpaca premium",
    price: 1800,
    category: "bombilla",
    image: "/mate-straw-bombilla-silver.jpg",
  },
  {
    id: 4,
    name: "Combo Potrero",
    description: "Mate + Yerba + Bombilla",
    price: 7500,
    category: "combo",
    image: "/mate-set-complete-kit.jpg",
    customizable: true,
    customizationPrice: 800,
  },
  {
    id: 5,
    name: "Yerba Suave",
    description: "Yerba suave sin palo",
    price: 2800,
    category: "yerba",
    image: "/yerba-mate-package-smooth.jpg",
  },
  {
    id: 6,
    name: "Mate de Madera",
    description: "Mate artesanal de algarrobo",
    price: 3500,
    category: "mate",
    image: "/wooden-mate-gourd-artisan.jpg",
    customizable: true,
    customizationPrice: 800,
  },
  {
    id: 7,
    name: "Bombilla Acero",
    description: "Bombilla de acero inoxidable",
    price: 1200,
    category: "bombilla",
    image: "/stainless-steel-mate-straw.jpg",
  },
  {
    id: 8,
    name: "Combo Campeón",
    description: "Set completo premium",
    price: 9500,
    category: "combo",
    image: "/premium-mate-set-luxury.jpg",
    customizable: true,
    customizationPrice: 800,
  },
]

export const ALL_PRODUCTS = [
  ...FEATURED_PRODUCTS,
  {
    id: 9,
    name: "Yerba con Hierbas",
    description: "Yerba con blend de hierbas",
    price: 3200,
    category: "yerba",
    image: "/yerba-mate-herbs-blend.jpg",
  },
  {
    id: 10,
    name: "Mate Camionero",
    description: "Mate térmico para viajes",
    price: 5500,
    category: "mate",
    image: "/thermal-mate-travel-mug.jpg",
    customizable: true,
    customizationPrice: 800,
  },
  {
    id: 11,
    name: "Bombilla Pico de Loro",
    description: "Bombilla clásica curva",
    price: 1500,
    category: "bombilla",
    image: "/curved-mate-straw-classic.jpg",
  },
  {
    id: 12,
    name: "Combo Hinchada",
    description: "Para compartir con amigos",
    price: 12000,
    category: "combo",
    image: "/mate-sharing-set-friends.jpg",
    customizable: true,
    customizationPrice: 800,
  },
]
